### PR TITLE
Add desc for item, currency, weapon | add gold like dollars | add some feature for bank (use bank like stash) | better count item

### PR DESCRIPTION
**Pull request by RobiZona**
# Inventory in Lua System for VORPCore framework

## Requirements
- [VORP Core](https://github.com/VORPCORE/VORP-Core/releases)
- [VORP Inputs](https://github.com/VORPCORE/VORP-Inputs/releases)
- [VORP Character](https://github.com/VORPCORE/VORP-Character/releases)

## Original File 
- [VORP Inventory](https://github.com/VORPCORE/vorp_inventory-lua)

## How to install
* Download the lastest version of VORP Inventory
* Copy and paste ```vorp_inventory``` folder to ```resources/vorp_inventory```
* Add ```ensure vorp_inventory``` to your ```resource.cfg``` file
* To change the language go to ```resources/vorp_inventory/Config``` and change the default language, also you will have to edit the html file to change the text on the inventory menu

## Features
* Unique weapons in order not to duplicate them.
* Each weapon has its own ammo and can have diferent type of ammo.
* Each weapon has its own modifications. (:warning: Not implemented yet)
* When dropping or giving a weapon you give it with all the modifications and ammo.
* It also has usable items.
* KLS.

## Extra Features
* All features from vorp_inventory_lua 1.0.7
* Description of all items in DB
* Gold item like Dollars (You can give and drop item)

image
image
image

## Wiki
[Wiki VORP Inventory](http://docs.vorpcore.com:3000/vorp-inventory)

## Credits
- To [Val3ro](https://github.com/Val3ro) for the initial work.
- to [Emolitt](https://github.com/Emolitt) and [Outsider](https://github.com/outsider31000) for finishing/testing.   
- Credits to Vorp Team for creating the C# version and [Local9](https://github.com/Local9).

### CODE REVIEW

**Comment by outsider31000** [comment]
image

what's this? why is it named rz in the vorp_inventory ?

image

why change this? 

also, gold has been added to the metadata inventory you can see it in the Trello.

can you show me a video of all this working on a live server?

**Comment by outsider31000** [comment]
also where is in the config to disable gold ?

**Comment by outsider31000** [comment]
1- You do realize this is for everyone to use right?
If you want to make modifications make sure if fits everyones needs not just yours.

2- For the rz bank that has nothing to do with vorp. Do that on your server. Events must be vorp compatible.

Why would I let an event in vorp inventory  when its for other scripts? That don't even exist?.

3- For the item description  that is okay. I would accept that pr only. But you added 1 pr with 21 commits so i cant merge it.

4- For the character max thats not the best way to do it. Why would a server owner have to give acces to admins to the servers DATABASE? So only the owner can change this, when a command its easy and saves all this work.

5 - most servers dont use gold if there's no config to disable then why should a server have gold?

That being said you have 21 commits in 1 pull request.

You need to Change it to 3 pul request for each feature  so I can accept what we think it fits **everyones needs**

Also i do thank you for all the pull requests.

**Comment by RobiZona** [comment]
1- You do realize this is for everyone to use right?
If you want to make modifications make sure if fits everyones needs not just yours.
`but it is compatible with all, the only thing to add is whether or not you want to use gold in your inventory as dollars`

2- For the rz bank that has nothing to do with vorp. Do that on your server. Events must be vorp compatible.
`is vorp compatible, i need to change it in vorp_bank`

3- For the item description that is okay. I would accept that pr only. But you added 1 pr with 21 commits so i cant merge it.
`sorry, is first time for me using github, do you need all desc modify in 1 commit?`

4- For the character max thats not the best way to do it. Why would a server owner have to give acces to admins to the servers DATABASE? So only the owner can change this, when a command its easy and saves all this work.
`true, i can add command for change (true/false) in DB`

5 - most servers dont use gold if there's no config to disable then why should a server have gold?
`i can add config.gold`

You need to Change it to 3 pul request for each feature so I can accept what we think it fits everyones needs
`i can try, it's okey if i do it now with all updates or I have to do it all over again?`

Also i do thank you for all the pull requests.
`sorry for all commits, i have to learn how to use github well`

**Comment by outsider31000** [comment]
What i meant is , this needs to fit everyones needs. You did this to your server cause thats what you want in your server that doesnt mean is what others want.

The events `must be renamed to vorp and be used with vorp_official scripts.`  
If theres no vorp bank to use them then I cant merge.

For gold there needs to be a config if false dont display gold in inventory

For the commits you must get the original script and change one feature at the time and pr one at the time.
1 pr for feature.

Or They can all be merged togheter as long it does what i mention and TESTED.

For the count thing `leave it round.` If owners whant to use 10000/10000 thats up to them. 

So fix all this  so I can merge it.

**Comment by outsider31000** [comment]
and you should do the same here. make a new pr for each feature this one cant be merged anymore. it has conflicts i have updated another old pr.

**Comment by AndrewR3K** [comment]
I would highly recommend always trying to make smaller prs with each feature rather than all in one shot. 

This makes it more reasonable for us to review and ensure any changes are what the community wants/needs.

I would start a new pr with the features that have been approved in the above convos.

**Comment by RobiZona** [comment]
ok, i'm removing bank functions and adding only gold function with config choose and descriptions of items, i'll do a new pr for clean work

**Comment by RobiZona** [comment]
finish, is not in conflict with css and en_lang, i update last version with transition

**Comment by AndrewR3K** [comment]
You have code conflicts you need to resolve before this can be considered even remotely ok to be merged.

**Comment by RobiZona** [comment]
but is not in conflict, i only added 1 line in en_lang for notify and in css i added description for html, i change it but still conflict

**Comment by AndrewR3K** [comment]
This is why I said above that I would recommend making a new branch with the latest changes and then adding your updates and create a new, clean, PR.

But this shows that you have many changes and that you do indeed have a conflict. 
image

**Comment by RobiZona** [comment]
These are not conflicts, how can i do?

Immagine 2022-06-24 224533
Immagine 2022-06-24 224551

**Comment by RobiZona** [comment]
and 2 hours ago i returned in original version of files

**Comment by AndrewR3K** [comment]
Start with a new, fresh, branch and raise a new pr, close this one its really messy.

**Comment by RobiZona** [comment]
ok ok

**Comment by AndrewR3K** [comment]
put your new code changes into the new branch you make. But ONLY add your changes, dont just copy/paste the files

**Comment by AndrewR3K** [comment]
Thanks!

**Pull request closed without merging**
