### PR TITLE
Delete dropped items

### PR DESCRIPTION
**Pull request by DerHobbs**
Permanently delete dropped items after a certain amount of time if you wish.

### CODE REVIEW

**Comment by outsider31000** [comment]
did  you test this when you go away from the object?
that entityhandleid is an entity id or netid ? cause if you go away and comeback it should not delete as the entity id have changed. 
if you can test.

**Comment by DerHobbs** [comment]
I did, dropped items in Saint Denis, then to blackwater and waited for the time when I return, they're gone.

**Comment by outsider31000** [comment]
try again without waiting and let me know, cause it cant delete the item cause it doesnt exist anymore  once you go away , it the entity id is lost and thats why we have netids assuming that id is not net id.

**Comment by RealStonerGamer** [comment]
> try again without waiting and let me know, cause it cant delete the item cause it doesnt exist anymore once you go away , it the entity id is lost and thats why we have netids assuming that id is not net id.

i just tested it like 15 times in a row each way set to 30 sec in timer then dropped items teleported to Tumbleweed and then waited 1 min came back gone every time 

dropped items then went to tumbleweed and right back and items all got removed not issue 
granted that is on a test server with no other player but me i will test on a live server and see if any issues 

this was tested on a fresh vorp prebuild  no edits

**Comment by outsider31000** [comment]
did you test with 2 people ? leave the are and see if it deletes for both

**Comment by RealStonerGamer** [comment]
> did you test with 2 people ? leave the are and see if it deletes for both

no like just said i will test tonight in alive setting with other players 1st tests where done just by my self  no other players

**Comment by RealStonerGamer** [comment]
i will test with 2 now before live test

**Comment by RealStonerGamer** [comment]
so with 2 players if you drop a item and both players leave it and come back after waiting it is still there and can not be removed but if the player is still around it the item when the timer ends it will be removed for all 

so the player that drops the item needs to stay by it for the timer to finish or the item is not removed  for anyone

**Comment by RealStonerGamer** [comment]
if timer is low enough then should not be a huge issue

 but still dose not fully fix the issue of it staying on the gourd forever when the id changes

**Comment by outsider31000** [comment]
like isaid above it cant delete becuase it does not exist  when you leave.
setting th time lower will not have any purpose might as well have a delete function with config drop and delete right a way 
thanks for testing

**Comment by RealStonerGamer** [comment]
> like isaid above it cant delete becuase it does not exist when you leave. setting th time lower will not have any purpose might as well have a delete function with config drop and delete right a way thanks for testing

np man yea was thinking the same thing we might end up doing that our self as we have 1000's of items dropped in towns and we ride to them and see boxes all over lol so might set to remove on drop so there is no time to pick up then no more boxes on ground lol

**Pull request closed without merging**
