### PR TITLE
Item description

### PR DESCRIPTION
**Pull request by CriMsOnN**
That should fix item description not showing on the ui.

https://i.imgur.com/WONVJaZ.png
https://i.imgur.com/Ue6P329.png

### CODE REVIEW

**Comment by outsider31000** [comment]
Make sure it wont override it.

**Comment by outsider31000** [comment]
Is this actually an item that you added metadata with code or you did manually?   Best  way to test is vorp mining add items description  and use it to test if metadata will override if you can please.
Im on holidays i can test it.

**Comment by CriMsOnN** [comment]
I just added metadata on the item through db. I also just checked for pickaxe and the description changed to Durability = 98.

**Comment by outsider31000** [comment]
Thank you.

**Pull request merged**
