### PR TITLE
Add option to clean inventory after detath

### PR DESCRIPTION
**Pull request by cl3i550n**
- Just additions, no existing changes.
```
  ClearOnRespawn = {
    Active   = false,        -- Active this module
    AllMoney = false,    -- Clear all money
    Gold     = false,        -- TRUE ONLY IF UseGoldItem = true
    Weapons  = false,    -- Clear all Weapons
    Items    = false         -- Clear all Items
  },
```

### CODE REVIEW

**Comment by outsider31000** [comment]
while appreciate the effort , this is not the right way to  make this feature,
 you sending events in `for loops`  from `client to server`  and deciding waht weapons to remove in the client which is hacked easly by cheat menus 

and other things  that i cant seem to understand where nothing in the code you added comes from where people press Respawn.

**Comment by outsider31000** [comment]
and also the variavle Active if people by mistake leave them both to true it will deleted and create drops , meaning it will delete and drop too.

**Comment by cl3i550n** [comment]
> and also the variavle Active if people by mistake leave them both to true it will deleted and create drops , meaning it will delete and drop too.

So the option to drop items must be removed, because it's the same thing... I just duplicated the existing functions and removed the option to drop on the ground

**Comment by outsider31000** [comment]
yeah i see, but thats the thing , if its a bad implemnetiation already by prebious creators,  pull requests must be at least better, because to merge the same bad code theres no point.

**Comment by cl3i550n** [comment]
The event E to respawn is called in VORP_CORE

image

**Comment by cl3i550n** [comment]
> yeah i see, but thats the thing , if its a bad implemnetiation already by previous creators, pull requests must be at least be better, because to merge the same bad code theres no point.

Huumm.. I didn't know that.

**Comment by outsider31000** [comment]
> The event E to respawn is called in VORP_CORE
> 
> image

yes thats a bad implementation by previous creators , the API will do all that, theres no reason to do repeated code when subItem and subWeapon does the ssame thing  and thats why we have getUserInventory , this isnt the way, to use a loop and send  net events over and over to server just to delete stuff.

**Comment by cl3i550n** [comment]
> > The event E to respawn is called in VORP_CORE
> > image
> 
> yes thats a bad implementation by previous creators , the API will do all that, theres no reason to do repeated code when subItem and subWeapon does the ssame thing and thats why we have getUserInventory , this isnt the way, to use a loop and send net events over and over to server just to delete stuff.

In the first moment I had done this.... better?

RegisterServerEvent("vorp_inventory:ClearItemsAfterDeath", function(type, targetID)
    local _source = source

    if not VorpCore.getUser(targetID) then
        return
    end

    if type == "items" then
        local inv = VorpInv.getUserInventory(targetID) --getcharinventory
        for key, inventoryItems in pairs(inv) do
            VorpInv.CloseInv(targetID)
            VorpInv.subItem(targetID, inventoryItems.name, inventoryItems.count)
        end
        VorpCore.NotifyRightTip(targetID, "Suas coisas cairam no chão e você perdeu!", 5000)
    elseif type == "weapons" then
        local weaponsPlayer = VorpInv.getUserWeapons(targetID) --getloadoutcharweapons
        for key, value in pairs(weaponsPlayer) do
            local id = value.id
            VorpInv.subWeapon(targetID, id)
            exports.oxmysql:execute("DELETE FROM loadout WHERE id=?", { id })
            TriggerClientEvent('syn_weapons:removeallammo', targetID)  -- syn script
            TriggerClientEvent('vorp_weapons:removeallammo', targetID) -- vorp
        end
        VorpCore.NotifyRightTip(targetID, "Suas coisas cairam no chão e você perdeu!", 5000)
    end
end)

**Comment by outsider31000** [comment]
you had done that?  thats a copy from vorp admin , you  didnt do that
image

**Comment by cl3i550n** [comment]
> you had done that? thats a copy from vorp admin , you didnt do that

not done of create, google translater..

**Comment by outsider31000** [comment]
I have made this feature and more and I will merge it tomorrow so dont worry about it.
 but thanks for the effort of course.
image

**Comment by cl3i550n** [comment]
> I have made this feature and more and I will merge it tomorrow so dont worry about it.
>  but thanks for the effort of course.
> image
> 
> 

Wooow nice! Thanks Outsider.

I'm learning little by little, I apologize in some cases not best code writing.

**Comment by outsider31000** [comment]
no need to apologise  appreciate the effort

**Comment by cl3i550n** [comment]
> 
Thanks, my development area is React/ReactNative android and iphone development. Kotlin and SWITFT too. Lua is novity.

**Pull request closed without merging**
