### PR TITLE
Removed a lot of boilerplate + stabilization of horses inventories

### PR DESCRIPTION
**Pull request by CrimsonFreak**
So in html/js/secondaryInvScript.js there was that huge piece of code that was basically the same thing 10 times... I made it almost systemic now, and it's still supporting everything.

I also got rig of the ifs on type (use a switch ffs) that were serving no purpose whatsoever.

Also instead of creating 10 variables (horseId, storeId, etc) I kept only one "Id" that's gonna be assigned to every field possibly required by any NUI callback and since only one is required at a time, you don't need to keep track of all of them now. To do this I also has to change every field name in NUI messages. 

It works with the horses, carts, and custom inventories for sure, I didn't do any extensive testing on everything else but it just works like that, and also improved the stability of the UI. We used to see the horses inventories in the custom ones, which is fixed now, also, the second inventory was sometimes draggable too, which doesn't happen anymore.

### CODE REVIEW

**Comment by outsider31000** [comment]
I have never heard of any issue regarding custom inventories interfering ,nor do I have any issue with it, note that users are responsible for the use of the API,
although if you can provide steps of reproduction and be sure that you are talking about vorp_stables and vorp API being used please post them here and how it's being used...
if its regarding other scripts you need to contact the creators of course.

as for the rest it all seems about right, but since I dont have all of those scripts to test and I assume neither do you, im not sure how you want this to be merged without being tested on your end?

**Comment by CrimsonFreak** [comment]
Sure, since we've had some issues I fixed it and I reckoned you guys might want to have it but if I'm the only one experiencing issues then sure, that PR is useless.
Here are the repro steps : 
- Custom script registering shared inventory : `inv.registerInventory(businessName, businessName, -1, true, true, true, null, null, null, null);`
- Then opens it from custom server event : `inv.OpenInv(source, name);`
- Everything works just fine when we set `Config.StablesSlots = 1` in vorp_stables
- With a value higher than 1, players with access to the custom inventory has them inverted (custom shows in Horse and Horse in custom)
- players with no access to the custom inventory sees an empty inventory in their Horse.

I couldn't fully put my finger on what went wrong here, but it's fixed with those changes
Note that I've forgot to include the updated NUIService.lua in that PR, I'll need to append it if you're gonna do anything.

Like I said I've tested some of them but not every single one, but it was a game breaking bug for us so I did what I could. I'm absolutely not entitled to a merge, I just share what I've found out. :)

**Comment by outsider31000** [comment]
inv.registerInventory(businessName, businessName, -1, true, true, true, null, null, null, null);

id must be unique for each inv created ,  and then you have -1 for ?

yeah you changed the code of 7 8 scripts so it needs to be tested.

**Comment by CrimsonFreak** [comment]
`InventoryAPI.registerInventory = function(id, name, limit, acceptWeapons, shared, ignoreItemStackLimit, whitelistItems,
										  UsePermissions, UseBlackList, whitelistWeapons)`
										  
-1 here stands for the max of objects that can go in (for instance no limit at all)

I get you point, once I've got it fully tested I'll PR again

I'm also working on the possibility to display 2 custom inventories rather than only the Player one and the Custom one. If that's of any interest to you I'll PR that too when done.

**Comment by CrimsonFreak** [comment]
Well I'm gonna find them to test no worries

Like I said I forgot the NUI controller update, that's why I closed it :)

I have something else in the pipes, I'll make sure to do a proper PR this time, with full doc and all. Sorry for bothering you with this broken one.

**Comment by outsider31000** [comment]
there are more things you didnt take in consideration , but , i made some changes because we changing to a new version 
so just  build off of that  if you wish , you can see i left the stores events because they are different 
just like gives and pick ups are differente  some accept floats others dont etc...

**Comment by outsider31000** [comment]
https://github.com/VORPCORE/vorp_inventory-lua/compare/27f0fa582d76...8e654f1ad8e3
heres my "safe" changes. for reference

**Comment by CrimsonFreak** [comment]
Yeah I've seen you made changes today, I didn't looked into it yet.
For instance I made those changes because I was gonna go for inventory based stores. Which are being heavily tested right now.
Ti go a bit into details, I have a custom script that manages businesses, the goal is that the owner can fill the shop with their items, or the ones for their business inventory, and give them a price.
For that purpose I modified the api on my end for it to accept the opening of 2 custom inventories, rather than only one and the character inventory.
I also slightly modified the UI so the price can be displayed on the bottom left of the item, next to the quantity.
The prices are stored in the metadata and removed on buy so it doesn't affect the stacking. For the weapons I store them in the components column for I didn't find any better way to do so.

It's basically working now, despite some bugs remaining, and a lot of cleaning to do, but I've done far more changes those last 3 days than I first shown in the PR.
I've tried my best to keep compatibility but as I said, there is still some cleaning to do before I can even think about sharing it.
Anyway I don't know if you're even gonna want to take the risk to merge with that much modifications, but I'll still submit it when I'm done so you can see for yourself.
Sorry again for that PR that shouldn't have happened in the first place. Cheers

**Comment by outsider31000** [comment]
id say best to keep the changes to your self if its something you did to work only for you yes.

**Pull request closed without merging**
