### PR TITLE
Possible implementation of a death config for preventing inventory access

### PR DESCRIPTION
**Pull request by Bobertsawesome**
Not sure if this would be the "right way" to do it or not, since it's running in the thread.

Confirmed working though. Will close the UI if the player is killed/dies with it open. Closes the UI if they try to open it while dead.

### CODE REVIEW

**Comment by rmrsnpdr** [comment]
the camera thing when died if u can move it it would be great.

**Comment by Bobertsawesome** [comment]
> the camera thing when died if u can move it it would be great.

That would be part of vorp-core-lua

**Comment by outsider31000** [comment]
Why are there so many commits and reverts

**Comment by Bobertsawesome** [comment]
I have no idea how to use GitHub is why lol.

**Pull request merged**
