### PR TITLE
new pr for descriptions and gold use

### PR DESCRIPTION
**Pull request by RobiZona**
descriptions of items are in DB
desc of weapons is in config.lua
desc of dollars and gold are in html

for use gold like dollars go in config.lua and config.js and put UseGoldItem = true

### CODE REVIEW

**Comment by outsider31000** [comment]
this looks okay, have you tested it?

**Comment by outsider31000** [comment]
image
 this needs to support the description for the inventory too no?
also what about API to give an item? does it have a place for description? will other scripts break if not? @RobiZona

**Comment by RobiZona** [comment]
no this command is the basic one right? does not give problems with the changes 
additems command works because when you put 'true' in 'users' for have multicharacter, in 'character' create new line, so every player have inventory linked by charid and identifier

**Comment by outsider31000** [comment]
This command is to give items. Nothing to do with characters? You added ability to items to have description right?

**Comment by outsider31000** [comment]
Also i guess its no needed players need to do it manually on the DB. Forget what I said.

**Comment by outsider31000** [comment]
Where do you add description? Theres no weapons on the DB

**Comment by RobiZona** [comment]
ah I understand, no no, it works without problems because it goes to give you the item, the description takes it from the database automatically, or at least, in the test it did not give me any problems

**Comment by outsider31000** [comment]
This is only for items or weapons too?

**Comment by RobiZona** [comment]
for weapon description is in config.lua, and is the same for all weapons, for example i use "use with caution"

**Comment by RobiZona** [comment]
in next update i can try to add description for each weapon in config

**Comment by outsider31000** [comment]
Thats ehat i meant have 1 description for al weapons dont make sense. Anyways ill test tomorrow.

**Comment by RobiZona** [comment]
i know, i can remove it and add in next update all desc for each weapon

**Comment by outsider31000** [comment]
should wait for that then?

**Comment by RobiZona** [comment]
yes. thank you, soon start

**Comment by outsider31000** [comment]
ok thanks. I will wait. I tested it a bit and seems to be working. but I want to wait for that. so people don't have to update twice.

**Comment by RobiZona** [comment]
there is a problem, if I don't go to put a description for the weapons, it is written under "undefined" so you have to force a description the same for all the weapons, I can put "weapon" for now and then I'll try to make a description for each weapon by adding it to the config for each weapon

**Comment by RobiZona** [comment]
in the meantime I try to do it

**Comment by outsider31000** [comment]
No worries ill wait.

**Comment by RobiZona** [comment]
@outsider31000  did it

**Pull request merged**
