### PR TITLE
Add weapons cache indexed by char.

### PR DESCRIPTION
**Pull request by systemNEO**
`InventoryAPI.getUserWeapons()` was very very slow if thousands of weapons exists on the server because to get the weapons of the char you have to loop all weapons and filter by char. This results in high process times on servers with 200 and more simultaneously playing players.

This adds a cache indexed by char so `InventoryAPI.getUserWeapons()` can directly return all char weapons WITHOUT looping all weapons.

To realize this cache all places where weapons will be added/removed from `UserWeapons` are extended to handle the new cache. We were able to reduce hitch warnings drastically.

We have tested it on @DerHobbs server (with more than 200 players) successfully. 

If you have questions or want to talk feel free. Since this is a complex change you could also talk about it directly in a talk. I have some questions (see TODO in changed code).

### CODE REVIEW

**Comment by outsider31000** [comment]
i'll be reviewing this and I got couple questions 

do you have the logs saying that inventory was throwing hitch warnings ? i need to see these logs  and the events that were triggerred.

**Comment by outsider31000** [comment]
I currently have loads of players too and so does others and about 33 k of loadout information , I do not have any hitch warnings.
did you also had your inventory up to date? 
 there was a patch that only loads weapons from players that are  in game as to before was loading all these 33k into memory but even though  still not had any hitch warnings 

did you had these hitch warnings opening other scripts that were probably custom made?

all these come into play , I cannot simply merge something based on your issues if you understand what I mean

**Comment by systemNEO** [comment]
As for the hitch warnings, @DerHobbs  reported that to me. We didn't make any recordings of them, though. However, they were so bad that we had to temporarily disable a feature completely. The hitch warnings occurred when other resources used `getUserWeapons()`, too. This means that if this method is called more often, it causes performance problems due to the unperformant function. The patch that only loads weapons from players who are currently online is not enough. Please imagine the following: 

A server runs for e.g. 6 hours without restarting. During this time about 500 different players are playing. Each player has on average 3 weapons. So that's 1500 weapons at the end of the time. `getUserWeapons()` searches these 1500 weapons at every call. This happens for example when someone opens the inventory. It also happens when resources use the VORP API. Inconveniently, if 10 players trigger `getUserWeapons()` in the same second, then 15000 weapons are searched in total. If with 200 simultaneous players this happens even more often, e.g. only 20 players in the same second, then already 30000 weapons are searched. This can cost up to 200ms (or more) in total. And then there are hitch warnings.

From a performance point of view this is an absolute no-go. I've been working as a developer for more than 20 years and I've learned that such performance issues can quickly become unpleasant. For example, if other places in the code have such small performance debts, then they can add up and become dramatic. This should be avoided.

We use the API provided by VORP. The API is public and meant for other resources to use. Correct me if I am wrong. According to this, this API should also be reasonably performant. Since it is not at this point, I have taken the trouble and volunteered to help improve the API. So if you're insinuating that I'm just doing this out of self-interest for my resources, you're certainly not wrong about that. I want my resources to run performantly. While programming I noticed that `getUserWeapons()` is not performant. And in the spirit of OpenSource, I've invested time and am making the improvement available to everyone, not just me and my resource. I think it's even a good drive to improve things if you want to get ahead yourself and let others share in it. Don't you think so?

**Comment by outsider31000** [comment]
based on what you said:
* `However, they were so bad that we had to temporarily disable a feature completely. The hitch warnings occurred when other resources used getUserWeapons()`

if they are so bad , I have no records of people complaining nor I have any issues with it so far (it doesnt mean that the issue dont exist), but so far we have no such issue and thats why  we need more information to make sure this issue  you say you have its not from other scripts that are missusing the API...

If you can provide us with something prooving what you saying, then we can work toghether to improove or fix
  
should be easy eough using the profiler tool you can see where  does the hitch comes from , and then we can verify the code that is used

**Comment by systemNEO** [comment]
Okay I will try to reproduce it (because we will do this not anymore on production systems on prime time). I take some time to create test cases and make measurements. Keep in mind that the profiler currently seems to be buggy. I hope CFX will fix it soon.

Important: Found this during resolving conflicts after your last commits. There is a wrong variable name in `InventoryAPI.giveWeapon()`, see Screen please.
image

**Comment by systemNEO** [comment]
I have created test cases to measure the speed of `getUserWeapons()`.

The case simulates
- 500 users that where logged in over time
- each user has 3 weapons
- peak of 40 calls of `getUserWeapons()` per second (e.g. 40 users open their inventory in the same time - yes, this is possible!)

This results in 
image

You can see that the current style is up to 16 times slower then the optimized style.

Now let's assume that another resource also uses `getUserWeapons()` very intensively, e.g. also 40 times a second. Let's assume a server has a lot of players and over the time until the server restart 1000 different players instead of 500 have logged in. Then it is no longer about 30ms, then it is 120ms (30ms x2 for other resource, 2x for double players).  **THAT IS AN ABSOLUTE NO-GO FOR A PUBLIC API.** And keep in mind I have tested this on my local machine (AMD Ryzen 9 3900XT 12-Core Processor, 4150 MHz, 12 Core(s), 24 logical Core(s)) - I do not think that every server has this specs (some maybe better ;) but the most will be worse).

Below is the code for the measurements so you can follow along.

If you have questions or I can help further then feel free. I am happy to help and share my 20+ years of know-how.

PS: Do not forget to fix wrong variable name (see my last comment above), please.

```lua
UsersWeapons = {} -- Current cache
UserWeaponsPerChar = {} -- New optimized cache
SimulatedUsers = {} -- Saves the used char ids for later usage in test to randomly select a char id

local unique_weapon_id = 0 -- Simulated weapon id counter
local weapons_total = 0

function resetCache()

    UsersWeapons = {
        default = {}
    }

    UserWeaponsPerChar = {
        default = {}
    }

    SimulatedUsers = {}

    weapons_total = 0
end

-- Builds the cache for this test.
---@param users_count number
---@param weapons_per_user number
function simulateAddWeapons(users_count, weapons_per_user)

    resetCache()

    for i = 1, users_count do

        local identifier = "steam:" .. i
        local charidentifier = "char:" .. i

        if not UserWeaponsPerChar["default"][charidentifier] then
            UserWeaponsPerChar["default"][charidentifier] = {}
        end

        table.insert(SimulatedUsers, {
            identifier = identifier,
            charidentifier = charidentifier
        })

        for j = 1, weapons_per_user do

            unique_weapon_id = unique_weapon_id + 1

            local weapon = {
                name = "Simulated weapon " .. unique_weapon_id,
                id = unique_weapon_id,
                propietary = identifier,
                charidentifier = charidentifier,
                used = false,
                ammo = 100,
                desc = "desc",
            }

            function weapon:getId()
                return self.id
            end

            function weapon:getPropietary()
                return self.propietary
            end

            function weapon:getCharId()
                return self.charidentifier
            end

            function weapon:getName()
                return self.name
            end

            function weapon:getUsed()
                return self.used
            end

            function weapon:getAllAmmo()
                return self.ammo
            end

            function weapon:getDesc()
                return self.desc
            end

            UsersWeapons["default"][unique_weapon_id] = weapon
            UserWeaponsPerChar["default"][charidentifier][unique_weapon_id] = true -- Only remember the id instead of the whole object twice

            weapons_total = weapons_total + 1
        end
    end
end

---@param identifier string
---@param charidentifier number
---@param cb function
function getUserWeapons_simulateCurrentStyle(identifier, charidentifier, cb)
    --local _source = player
    --local sourceCharacter = Core.getUser(_source).getUsedCharacter
    --local identifier = sourceCharacter.identifier
    --local charidentifier = sourceCharacter.charIdentifier
    local usersWeapons = UsersWeapons["default"]

    local userWeapons2 = {}

    for _, currentWeapon in pairs(usersWeapons) do
        if currentWeapon:getPropietary() == identifier and currentWeapon:getCharId() == charidentifier then
            local weapon = {
                name = currentWeapon:getName(),
                id = currentWeapon:getId(),
                propietary = currentWeapon:getPropietary(),
                used = currentWeapon:getUsed(),
                ammo = currentWeapon:getAllAmmo(),
                desc = currentWeapon:getDesc()
            }
            table.insert(userWeapons2, weapon)
        end
    end
    cb(userWeapons2)
end

---@param identifier string
---@param charidentifier number
---@param cb function
function getUserWeapons_simulateOptimizedStyle(identifier, charidentifier, cb)

    local charWeapons = UserWeaponsPerChar['default'][charidentifier]

    ---@type WrappedCharWeapons[]
    local wrappedCharWeapons = {}

    for weaponId, _ in pairs(charWeapons) do
        local currentWeapon = UsersWeapons["default"][weaponId]
        if currentWeapon:getPropietary() == identifier then
            local wrapped_weapon = {
                name = currentWeapon:getName(),
                id = currentWeapon:getId(),
                propietary = currentWeapon:getPropietary(),
                used = currentWeapon:getUsed(),
                ammo = currentWeapon:getAllAmmo(),
                desc = currentWeapon:getDesc()
            }
            table.insert(wrappedCharWeapons, wrapped_weapon)
        end
    end

    cb(wrappedCharWeapons)
end

---@return number
function getTimeStampInMs()
    return os.clock() * 1000
end

---@param test_name string
---@param users_count number
---@param weapons_per_user number
---@param calls_per_second number
---@param test_function fun(identifier: string, charidentifier: number, cb: function)
function runTestCaseDistributed(test_name, users_count, weapons_per_user, calls_per_second, test_function)

    local call_interval_ms = 1000 / calls_per_second
    local calls_to_go = calls_per_second

    local cb = function(found_weapons)
        --print("Found weapons: " .. #found_weapons)
    end

    local p = promise.new()

    Citizen.CreateThread(function()

        local measured_time_total_in_ms = 0
        local simulated_users_count = #SimulatedUsers

        while calls_to_go > 0 do

            calls_to_go = calls_to_go - 1

            local random_user = SimulatedUsers[math.random(1, simulated_users_count)]
            local identifier = random_user.identifier
            local charidentifier = random_user.charidentifier

            local start = getTimeStampInMs()
            test_function(identifier, charidentifier, cb)
            local measured_time_for_function_in_ms = getTimeStampInMs() - start

            measured_time_total_in_ms = measured_time_total_in_ms + measured_time_for_function_in_ms

            Citizen.Wait(call_interval_ms)
        end

        print("")
        print(test_name .. " finished (distributed over time)")
        print("   Calls per second: " .. calls_per_second)
        print("   Users (over time): " .. users_count)
        print("   Weapons per user: " .. weapons_per_user)
        print("   Weapons total: " .. weapons_total)
        print("   Total time: " .. measured_time_total_in_ms .. "ms")
        print("   Average time per call: " .. (measured_time_total_in_ms / calls_per_second) .. "ms")
        print("")

        p:resolve()
    end)

    Citizen.Await(p)
end

---@param test_name string
---@param users_count number
---@param weapons_per_user number
---@param calls_per_second number
---@param test_function fun(identifier: string, charidentifier: number, cb: function)
function runTestCaseAtOnce(test_name, users_count, weapons_per_user, calls_per_second, test_function)

    local cb = function(found_weapons)
        --print("Found weapons: " .. #found_weapons)
    end

    local measured_time_total_in_ms = 0
    local simulated_users_count = #SimulatedUsers

    for i = 1, calls_per_second do
        local random_user = SimulatedUsers[math.random(1, simulated_users_count)]
        local identifier = random_user.identifier
        local charidentifier = random_user.charidentifier

        local start = getTimeStampInMs()
        test_function(identifier, charidentifier, cb)
        local measured_time_for_function_in_ms = getTimeStampInMs() - start

        measured_time_total_in_ms = measured_time_total_in_ms + measured_time_for_function_in_ms
    end

    print("")
    print(test_name .. " finished (at once)")
    print("   Calls per second: " .. calls_per_second)
    print("   Users (over time): " .. users_count)
    print("   Weapons per user: " .. weapons_per_user)
    print("   Weapons total: " .. weapons_total)
    print("   Total time: " .. measured_time_total_in_ms .. "ms")
    print("   Average time per call: " .. (measured_time_total_in_ms / calls_per_second) .. "ms")
    print("")
end

---@param test_users_count number
---@param test_weapons_per_user number
---@param test_calls_per_second number
function runTests(test_users_count, test_weapons_per_user, test_calls_per_second)

    -- 1. Build simulated cache
    simulateAddWeapons(test_users_count, test_weapons_per_user)

    print('')
    print('New test: distributed')
    print('Start', getTimeStampInMs())
    print('')

    runTestCaseDistributed('Current style', test_users_count, test_weapons_per_user, test_calls_per_second, getUserWeapons_simulateCurrentStyle)

    runTestCaseDistributed('Optimized style', test_users_count, test_weapons_per_user, test_calls_per_second, getUserWeapons_simulateOptimizedStyle)

    --print('')
    --print('New test: at once')
    --print('')
    --
    --runTestCaseAtOnce('Current style', test_users_count, test_weapons_per_user, test_calls_per_second, getUserWeapons_simulateCurrentStyle)
    --
    --runTestCaseAtOnce('Optimized style', test_users_count, test_weapons_per_user, test_calls_per_second, getUserWeapons_simulateOptimizedStyle)

    print('End', getTimeStampInMs())
end

Citizen.CreateThread(function()
    runTests(500, 3, 40)
end)
```

**Comment by systemNEO** [comment]
@outsider31000 What is your opinion about the test results?

**Comment by outsider31000** [comment]
it does improve slightly...
 I still think theres a better approach to this matter , by removing players data from the cache when they leave the server.
 then you would not have 500 users to iterate through, and its gonna be on the next update...
  
Since I patched it, to only add data if player has entered I never had any hitch and neither before that patch, blue server syn county still has that old way and he have no hitchs with 230 players.

I still think these was probably a miss use of the API

 so I find it very hard to beleive that's all. 
 
 anyways if it improves great.

**Comment by systemNEO** [comment]
Hey @outsider31000 

> I still think theres a better approach to this matter , by removing players data from the cache when they leave the server.

I agree with you. If you want I can try to create a solution for that?

Thanks & Best

**Comment by outsider31000** [comment]
sure go ahead thanks

**Pull request merged**
