### PR TITLE
Load weapon from db if not in cache.

### PR DESCRIPTION
**Pull request by systemNEO**
See issue https://github.com/VORPCORE/vorp_banking/issues/38

After server restart weapons without charidentifier are not loaded into cache. This fix try to load weapons that are not cached (like "on demand" to prevent performance issues).

### CODE REVIEW

**Comment by outsider31000** [comment]
They are `not` supposed to be loaded if theres no charidentifier...

thats why theres a check there ,
we dont need  to go again to query the database and load weapons that have no charidentifier and set them as empty when we could just remove the check on the first function  that would do the same thing.

we can't have it as empty , `the only column that can be empty is the steamidentfier `  and this is only for syn scripts.

in fact we should instead delete anything without charidentifer for precaution , although i have 50k of data in the DB and not a single weapon is missing the charidentifier that I just checked ,

thats why I say the issue seems to be  in the bank script

**Comment by systemNEO** [comment]
> They are `not` supposed to be loaded if theres no charidentifier...
> 
> thats why theres a check there , we dont need to go again to query the database and load weapons that have no charidentifier and set them as empty when we could just remove the check on the first function that would do the same thing.
> 
> we can't have it as empty , `the only column that can be empty is the steamidentfier ` and this is only for syn scripts like the weapons menu .
> 
> in fact we should instead delete anything without charidentifer for precaution , although i have 50k of data in the DB and not a single weapon is missing the charidentifier that I just checked ,
> 
> thats why I say the issue seems to be in the bank script

1) Why uses the bank script not the custom inventory function of vorp inventory?
2) If the charidentifier will not be nulled then the weapon will be in default inventory all the time. Then it must be ensured that it is not shown in the personal inventory of the user.
3) This bug is very old and was there before the new weapon cache was implemented. It is now transparent what the source of the bug is and my fix in the weapon cache solve the problem.

It is up to you. I'm tired of arguing with you all the time about sensible things that you obviously don't understand. Take it or leave it.

**Comment by outsider31000** [comment]
`It is up to you. I'm tired of arguing with you all the time about sensible things that you obviously don't understand. Take it or leave it.`
 you the one who dont understand that i am the project manager , if i ask questions its because its my duty, you dont get to have things merged  just because you make a pull request 

they will be merge if it think they are good if you cant understand that im in charge here you should not me making any  pull request

**Comment by systemNEO** [comment]
Your decision. 

I see myself then no longer responsible for the weapon cache. That's why I'm not available from now on, if there are problems with the inventory and the weapon cache again.

**Pull request closed without merging**
