### PR TITLE
fix(html/ui): validate that the quantity inputted is an int

### PR DESCRIPTION
**Pull request by Mycroft-Studios**

### CODE REVIEW

**Comment by outsider31000** [comment]
Was tests done like drop itmes item give and receive to other players? I can also test later.

**Comment by outsider31000** [comment]
You jave no friends : ( im your friend. Ill help later

**Review by rmrsnpdr — APPROVED** [review]

**Comment by rmrsnpdr** [comment]
do u need help to try it? haha

**Comment by Local9** [comment]
why so much copy and paste?

**Comment by outsider31000** [comment]
I cant pr this . as it's not a fix, if yall dont mind/have time and can give hand on how to fix it.  @Local9 @Mycroft-Studios  users would appreciate it.

**Comment by outsider31000** [comment]
this has been done.

**Pull request closed without merging**
