### PR TITLE
Remove metadata check

### PR DESCRIPTION
**Pull request by LandminenTester**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Motive for This Pull Request
Prevent failure of a lot vorp scripts that use the item count function

### Provide a brief explanation of why these changes are being proposed and what they aim to achieve.
The Decay update introduced a change where only items without metadata are counted. However, there is no functionality to count items both with and without metadata simultaneously. This modification renders the `ItemCount` function ineffective for many use cases and could break numerous scripts.  

Originally, this change was not part of the design, as evidenced in the code found in `server/services/inventoryApiService.lua` within the `InventoryAPI.getItemCount` function:  

```lua
-- get count of all items with or without metadata but can choose to get expired items
local itemTotalCount <const> = SvUtils.GetItemCount("default", identifier, itemName, percentage)
```  

Therefore, the part of the change introduced in the Decay refactor should be reverted to prevent disruptions to existing scripts.

### Explain the necessity of these changes and how they will impact the framework or its users.
With the current changes in this function potentially a lot of scripts could break, because of that this part of the refactor should be removed again

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi, I have a question, as to me thid dont make much sense, but perhaps you have a scenario in which I can't think of.

what does it matter how many  items with metadata you have if they are unique ?
like in what scenario you want to know how many you have when there could be stacks of items with diferent metadata from multiple scripts, where in each item, the variables are different in the metadata?


If anyone is using this export to get random items for metadata then **they are doing it wrong**(sure it did before, but it was wrong all along, there was no usage for it  they are unique items)

if I want to check metadata its either for specifc matching values(which has support) or I would need to use `getUserInventoryItems` so I can specifically get what I am looking for **in my script where the metadata was set** 

90% of the exports are not needed if you just use `getUserInventoryItems`  in your scripts, that is what the inventory basically does
these are just helpers to simplify code. anything advanced needs to be done in your scripts specially when it comes to metadata and now the decay system

it does not make sense to me getting a count of random items with metadata when they are unique to each script.I really do not see any scenario that this may fit because several servers are using hundreds of scripts.

these are the cases it makes sense to me.
- getting count of items expired or not expired/at desired percentage (i added this just as a helper I myself will not use it when dealing with decay, rather get all items and look for what I speciffically want because they are unique items)
- items with no expiration at all (where it makes the most sense)


but please if you have a usage case that I am missing,I am happy to hear. I can make tests as well if neded, my intent is never to break compability unless is for security purposes.

**Comment by LandminenTester** [comment]
You're essentially correct that when using `getUserInventoryItems()`, most of the exports become somewhat redundant. However, the reason for my pull request was the following use case:

Many scripts use this function as a simple and quick method to check whether a player has an item—completely ignoring whether the item has metadata or even which metadata it has. Let's take a **pickaxe** as an example. 

Many scripts use `getItemCount` as an initial check to determine if the player even has the item in their inventory. If they do, the script then specifically searches for that item (e.g., a pickaxe) and processes its metadata. However, due to the recent change requiring items to have no metadata for their count to be recognized, all scripts that rely on `getItemCount` as a method to check for the mere existence of such items now need to be updated.

This was the main issue I aimed to address with my PR.

**Comment by outsider31000** [comment]
Like I mentioned earlier, if scripts are using this export to retrieve items with metadata, that approach is incorrect. look at the case below.

Case 1:

- You're looking to determine if the player has a pickaxe without any metadata so that you can apply new metadata later. If the inventory has one such pickaxe, the correct count returned should be 1, indicating a suitable item for metadata application is available. **correct way**

However, if metadata is considered in the count, then the total becomes inaccurate. Suppose you have one pickaxe with existing metadata, the export will still return a count of one. But your requirement was for a pickaxe without metadata, as the intention is to add new metadata later. With the proposed changes, the count becomes misleading and wrong.

Metadata is unique, and counting items with metadata when you only need items without it complicates inventory management. Therefore, it is essential to use `getUserInventoryItems` and perform specific checks for metadata presence in your scripts to ensure accurate counts.

If an item already have metadata, then people need to pass the metadata in the export to get the correct item count for that specific metadata, and not a random one.

let me know if this makes sense to you, and if you understand why was it wrong in the first place.

**Comment by outsider31000** [comment]
I am going to allow this check to look for metadata items, which i think is wrong, im going to make a new export where we can actually separate what we want.

**Pull request closed without merging**
