### PR TITLE
some fix

### PR DESCRIPTION
**Pull request by RobiZona**
miss PlayerPedId()
check if weapon have serial number for desc

### CODE REVIEW

**Comment by outsider31000** [comment]
Playerpedid missing yeah, what about the other stuff you added?  You need to add a description to you pull request.

**Comment by outsider31000** [comment]
Either remove or explain why is it needed you to check twice serial number is empty string, which it will never be empty string
Those checks seems redundant.

**Comment by RobiZona** [comment]
because when you withdraw a weapon from a deposit, even if it has no serial number it appears in the description "serial number: ", in this way it checks the description and removes it if the serial is empty

**Comment by RobiZona** [comment]
this check is done on both the custom description and the default description

**Pull request merged**
